# lista de livros
livros = {
    # LIVRO 1
    'Torto Arado': {'paginas': '264', 'autor': 'Itamar Vieira', 'genero': 'Ficção', 'editora': 'todavia',
                    'preco': '36,9', 'avaliacao': '4,8', 'data': '07/08/2019', 'posicao': '1',
                    'sinopse': 'Nas profundezas do sertão baiano, as irmãs Bibiana e Belonísia encontram uma velha e misteriosa faca na mala guardada sob a cama da avó. Ocorre então um acidente. E para sempre suas vidas estarão ligadas ― a ponto de uma precisar ser a voz da outra. Numa trama conduzida com maestria e com uma prosa melodiosa, o romance conta uma história de vida e morte, de combate e redenção.'},

    # LIVRO 2
    'O homem Mais Rico da Babilonia': {'paginas': '160', 'autor': 'George S clason', 'genero': 'auto-ajuda', 'editora': 'HarperCollins',
                                       'preco': '13,89', 'avaliacao': '4.9', 'data': '04/08/2017', 'posicao': '2',
                                       'sinopse': 'Com mais de dois milhões de exemplares vendidos no mundo todo, O homem mais rico da Babilônia é um clássico sobre como multiplicar riqueza e solucionar problemas financeiros. Baseando-se nos segredos de sucesso dos antigos babilônicos ― os habitantes da cidade mais rica e próspera de seu tempo ―, George S. Clason mostra soluções ao mesmo tempo sábias e muito atuais para evitar a falta de dinheiro, como não desperdiçar recursos durante tempos de opulência, buscar conhecimento e informação em vez de apenas lucro, assegurar uma renda para o futuro, manter a pontualidade no pagamento de dívidas e, sobretudo, cultivar as próprias aptidões, tornando-se cada vez mais habilidoso e consciente'},

    # LIVRO 3
    'Mulheres que Correm com os Lobos': {'paginas': '576', 'autor': 'Clarissa Pinkola', 'genero': 'psicanalise',
                                         'preco': '35,90', 'editora': 'Rocco', 'avaliacao': '4.8', 'data': '17/09/2018', 'posicao': '3',
                                         'sinopse': 'Os lobos foram pintados com um pincel negro nos contos de fada e até hoje assustam meninas indefesas. Mas nem sempre eles foram vistos como criaturas terríveis e violentas. Na Grécia antiga e em Roma, o animal era o consorte de Artemis, a caçadora, e carinhosamente amamentava os heróis. A analista junguiana Clarissa Pinkola Estés acredita que na nossa sociedade as mulheres vêm sendo tratadas de uma forma semelhante. Ao investigar o esmagamento da natureza instintiva feminina, Clarissa descobriu a chave da sensação de impotência da mulher moderna. Seu livro, Mulheres que correm com os lobos, ficou durante um ano na lista de mais vendidos nos Estados Unidos. Abordando 19 mitos, lendas e contos de fada, como a história do patinho feio e do Barba-Azul, Estés mostra como a natureza instintiva da mulher foi sendo domesticada ao longo dos tempos, num processo que punia todas aquelas que se rebelavam. Segundo a analista, a exemplo das florestas virgens e dos animais silvestres, os instintos foram devastados e os ciclos naturais femininos transformados à força em ritmos artificiais para agradar aos outros. Mas sua energia vital, segundo ela, pode ser restaurada por escavações psíquico-arqueológicas nas ruínas do mundo subterrâneo. Até o ponto em que, emergindo das grossas camadas de condicionamento cultural, apareça a corajosa loba que vive em cada mulher. Clássico dos estudos sobre o sagrado feminino e o feminismo, o livro é o primeiro de uma série de longsellers da Rocco a ganhar edição com novo projeto gráfico e capa dura.'},

    # LIVRO 4
    'Do mil ao Milhao': {'paginas': '192', 'autor': 'Thiago Nigro', 'genero': 'finanças',
                         'preco': '14.90', 'editora': 'HarperCollins', 'avaliacao': '4.7', 'data': '10/11/2018', 'posicao': '4',
                         'sinopse': 'Em seu primeiro livro, Thiago Nigro, criador da plataforma O Primo Rico, ensina aos leitores os três pilares para atingir a independência financeira: gastar bem, investir melhor e ganhar mais. Por meio de dados e de sua própria experiência como investidor e assessor, Nigro mostra que a riqueza é possível para todos – basta estar disposto a aprender e se dedicar.'},

    # LIVRO 5
    'A revolucao dos bichos: um conto de fadas': {'paginas': '152', 'autor': 'george orwell', 'genero': 'Ficçao',
                                                  'preco': '12.90', 'editora': 'Companhia das Letras', 'avaliacao': '4.9', 'data': '10/01/2001', 'posicao': '5',
                                                  'sinopse': 'Escrita em plena Segunda Guerra Mundial e publicada em 1945 depois de ter sido rejeitada por várias editoras, essa pequena narrativa causou desconforto ao satirizar ferozmente a ditadura stalinista numa época em que os soviéticos ainda eram aliados do Ocidente na luta contra o eixo nazifascista. De fato, são claras as referências: o despótico Napoleão seria Stálin, o banido Bola-de-Neve seria Trotsky, e os eventos políticos - expurgos, instituição de um estado policial, deturpação tendenciosa da História - mimetizam os que estavam em curso na União Soviética. Com o acirramento da Guerra Fria, as mesmas razões que causaram constrangimento na época de sua publicação levaram A revolução dos bichos a ser amplamente usada pelo Ocidente nas décadas seguintes como arma ideológica contra o comunismo. O próprio Orwell, adepto do socialismo e inimigo de qualquer forma de manipulação política, sentiu-se incomodado com a utilização de sua fábula como panfleto. Depois das profundas transformações políticas que mudaram a fisionomia do planeta nas últimas décadas, a pequena obra-prima de Orwell pode ser vista sem o viés ideológico reducionista. Mais de sessenta anos depois de escrita, ela mantém o viço e o brilho de uma alegoria perene sobre as fraquezas humanas que levam à corrosão dos grandes projetos de revolução política. É irônico que o escritor, para fazer esse retrato cruel da humanidade, tenha recorrido aos animais como personagens. De certo modo, a inteligência política que humaniza seus bichos é a mesma que animaliza os homens. Escrito com perfeito domínio da narrativa, atenção às minúcias e extraordinária capacidade de criação de personagens e situações, A revolução dos bichos combina de maneira feliz duas ricas tradições literárias: a das fábulas morais, que remontam a Esopo, e a da sátira política, que teve talvez em Jonathan Swift seu representante máximo. "A melhor sátira já escrita sobre a face negra da história moderna." Malcolm Bradbury "Um livro para todos os tipos de leitor, seu brilho ainda intacto depois de sessenta anos." Ruth Rendell'},

    # LIVRO 6
    'Mentirosos': {'paginas': '272', 'autor': 'E Lockhart', 'genero': 'Ficçao',
                   'preco': '27.91', 'editora': 'Seguinte', 'avaliacao': '4.6', 'data': '03/10/2014', 'posicao': '6',
                   'sinopse': 'Na família Sinclair, ninguém é carente, criminoso, viciado ou fracassado. Mas talvez isso seja mentira. Os Sinclair são uma família rica e renomada, que se recusa a admitir que está em decadência e se agarra a todo custo às tradições. Assim, todo ano o patriarca, suas três filhas e seus respectivos filhos passam as férias de verão em sua ilha particular. Cadence - neta primogênita e principal herdeira -, seus primos Johnny e Mirren e o amigo Gat são inseparáveis desde pequenos, e juntos formam um grupo chamado Mentirosos. Durante o verão de seus quinze anos, as férias idílicas de Cadence são interrompidas quando a garota sofre um estranho acidente. Ela passa os próximos dois anos em um período conturbado, com amnésia, depressão, fortes dores de cabeça e muitos analgésicos. Toda a família a trata com extremo cuidado e se recusa a dar mais detalhes sobre o ocorrido… até que Cadence finalmente volta à ilha para juntar as lembranças do que realmente aconteceu. “Emocionante, bonito e devastadoramente inteligente, Mentirosos é absolutamente inesquecível.” - John Green, autor de A culpa é das estrelas'},

    # LIVRO 7
    'A garota do lago': {'paginas': '296', 'autor': 'Charlie Donlea', 'genero': 'Ficçao',
                         'preco': '12.50', 'editora': 'Faro EEditora', 'avaliacao': '4.7', 'data': '01/01/2017', 'posicao': '7',
                         'sinopse': 'Summit Lake, uma pequena cidade entre montanhas, é esse tipo de lugar, bucólico e com encantadoras casas dispostas à beira de um longo trecho de água intocada.Duas semanas atrás, a estudante de direito Becca Eckersley foi brutalmente assassinada em uma dessas casas. Filha de um poderoso advogado, Becca estava no auge de sua vida. Atraída instintivamente pela notícia, a repórter Kelsey Castle vai até a cidade para investigar o caso. ...E LOGO SE ESTABELECE UMA CONEXÃO ÍNTIMA QUANDO UM VIVO CAMINHA NAS MESMAS PEGADAS DOS MORTOS...E enquanto descobre sobre as amizades de Becca, sua vida amorosa e os segredos que ela guardava, a repórter fica cada vez mais convencida de que a verdade sobre o que aconteceu com Becca pode ser a chave para superar as marcas sombrias de seu próprio passado.'},

    # LIVRO 8
    'Orgulho e preconceito': {'paginas': '456', 'autor': 'Jane Austen', 'genero': 'Romance',
                              'preco': '48.90', 'editora': 'Antofagica', 'avaliacao': '4.5', 'data': '24/06/2021', 'posicao': '8',
                              'sinopse': 'Ao contrário de sua mãe, que anima-se diante de qualquer bonitão com uma boa herança à vista, Elizabeth Bennet não se deixa levar pelas aparências. Antes de considerar qualquer um como um bom partido, para além de fortuna e propriedades, Lizzie investiga aspectos que considera muito mais importantes: reputação e caráter. Por isso, ao ser apresentada ao rico e arrogante Fitzwilliam Darcy, sua única reação é o desprezo. Conhecê-lo melhor, porém, pode abalar as perspectivas de Elizabeth. Vítima de suas próprias imperfeições e preconceitos, Elizabeth é uma das personagens mais fascinantes da literatura. Inteligente e observadora, ela encarna uma versão alternativa do feminino de sua época: uma mulher que não se conforma às regras do jogo social, mas que as questiona a todo instante.. A nova edição da Antofágica, traduzida por Carol Chiovatto, traz ilustrações exclusivas de Jess Vieira e apresentação da escritora Bruna Vieira. Nos posfácios, Sandra Guardini, professora titular de Literatura Inglesa e Comparada (USP), oferece um panorama da vida e de obra de Jane Austen, e Jaqueline Sant ana, doutoranda em Sociologia (UFRJ), analisa a autora sob a perspectiva da chamada “literatura de mulherzinha”. Isadora Sinay, formada em Cinema e doutora em Literatura (USP), faz uma análise das representações audiovisuais da obra da autora.'},

    # LIVRO 9
    'O poder da açao': {'paginas': '256', 'autor': 'Paulo Vieira', 'genero': 'Ficçao',
                        'preco': '12.90', 'editora': 'Paulo Vieira', 'avaliacao': '4.7', 'data': '01/06/2015', 'posicao': '9',
                        'sinopse': 'Acorde para os objetivos que quer conquistar. Já aconteceu a você de se olhar no espelho e não gostar daqueles quilos a mais? De observar seu momento profissional somente com frustração? De se sentir desconectado dos seus familiares, dos seus amigos? Se você acha que essas são situações normais, pense de novo! Só porque isso acontece com várias pessoas não quer dizer que a vida deva ser assim. Só porque algo se torna comum, não significa que seja normal! Neste livro, Paulo Vieira lhe convida a quebrar o ciclo vicioso e iniciar um caminho de realização. Para isso, ele apresenta o método responsável por impactar 250 mil pessoas ao longo de sua carreira - e que pode ser a chave para o que você tanto procura. No decorrer destas páginas, o autor lhe entrega uma bússola. E para conseguir se guiar por ela você terá de assumir um compromisso com a mudança. Preparado? Aproveite todas as provocações e os desafios propostos nesta obra para conseguir, de fato, fazer o check-up completo sobre si mesmo. Acorde, creia, comunique, tenha foco, AJA! Pare de adiar sua vida e seja quem quer ser a partir de agora. Não existe outra opção. E está em suas mãos reescrever seu futuro.'},

    # LIVRO 10
    'O poder do hábito': {'paginas': '408', 'autor': 'Charles Duhhig', 'genero': 'Auto-ajuda',
                          'preco': '30.79', 'editora': 'Objetiva', 'avaliacao': '4.7', 'data': '24/09/2012', 'posicao': '10',
                          'sinopse': 'Durante os últimos dois anos, uma jovem transformou quase todos os aspectos de sua vida. Parou de fumar, correu uma maratona e foi promovida. Em um laboratório, neurologistas descobriram que os padrões dentro do cérebro dela mudaram de maneira fundamental. Publicitários da Procter & Gamble observaram vídeos de pessoas fazendo a cama. Tentavam desesperadamente descobrir como vender um novo produto chamado Febreze, que estava prestes a se tornar um dos maiores fracassos na história da empresa. De repente, um deles detecta um padrão quase imperceptível - e, com uma sutil mudança na campanha publicitária, Febreze começa a vender um bilhão de dólares por anos. Um diretor executivo pouco conhecido assume uma das maiores empresas norte-americanas. Seu primeiro passo é atacar um único padrão entre os funcionários - a maneira como lidam com a segurança no ambiente de trabalho -, e logo a empresa começa a ter o melhor desempenho no índice Dow Jones. O que todas essas pessoas tem em comum? Conseguiram ter sucesso focando em padrões que moldam cada aspecto de nossas vidas. Tiveram êxito transformando hábitos. Com perspicácia e habilidade, Charles Duhigg apresenta um novo entendimento da natureza humana e seu potencial para a transformação.'},

    # LIVRO 11
    'Mindset: A nova psicologia do sucesso': {'paginas': '312', 'autor': 'Carol S. Dweck', 'genero': 'autoajuda',
                                              'preco': '25.79', 'editora': 'Objetiva', 'avaliacao': '4.7', 'data': '24/01/2017', 'posicao': '11',
                                              'sinopse': 'Carol S. Dweck, ph.D., professora de psicologia na Universidade Stanford e especialista internacional em sucesso e motivação, desenvolveu, ao longo de décadas de pesquisa, um conceito fundamental: a atitude mental com que encaramos a vida, que ela chama de “mindset”, é crucial para o sucesso. Dweck revela de forma brilhante como o sucesso pode ser alcançado pela maneira como lidamos com nossos objetivos. O mindset não é um mero traço de personalidade, é a explicação de por que somos otimistas ou pessimistas, bem-sucedidos ou não. Ele define nossa relação com o trabalho e com as pessoas e a maneira como educamos nossos filhos. É um fator decisivo para que todo o nosso potencial seja explorado.'},

    # LIVRO 12
    'Pai rico, pai pobre': {'paginas': '336', 'autor': 'Kiyosaki Robert', 'genero': 'Finanças',
                            'preco': '34.00', 'editora': 'Altas Books', 'avaliacao': '4.9', 'data': '26/07/2017', 'posicao': '12',
                            'sinopse': 'Celebrando 20 anos como o livro n° 1 em finanças pessoais.A escola prepara as crianças para o mundo real? Essa é a primeira pergunta com a qual o leitor se depara neste livro. O recado é ousado e direto: boa formação e notas altas não bastam para assegurar o sucesso de alguém. O mundo mudou; a maioria dos jovens tem cartão de crédito, antes mesmo de concluir os estudos, e nunca teve aula sobre dinheiro, investimentos, juros etc. Ou seja, eles vão para a escola, mas continuam financeiramente improficientes, despreparados para enfrentar um mundo que valoriza mais as despesas do que a poupança.Para o autor, o conselho mais perigoso que se pode dar a um jovem nos dias de hoje é: “Vá para a escola, tire notas altas e depois procure um trabalho seguro.” O fato é que agora as regras são outras, e não existe mais emprego garantido para ninguém. Pai Rico, Pai Pobre demonstra que a questão não é ser empregado ou empregador, mas ter o controle do próprio destino ou delegá-lo a alguém. É essa a tese de Robert Kiyosaki neste livro substancial e visionário. Para ele, a formação proporcionada pelo sistema educacional não prepara os jovens para o mundo que encontrarão depois de formados.E como os pais podem ensinar aos filhos o que a escola relega? Essa é outra das muitas perguntas que o leitor encontra em Pai Rico, Pai Pobre. Nesse sentido, a proposta do autor é facilitar a tarefa dos pais. Quem entende de contabilidade deve esquecer seus conhecimentos acadêmicos, pois muitas das teorias expostas por Robert Kiyosaki contrariam os princípios contábeis comumente aceitos, e apresentam uma valiosa e moderna percepção do modo como se realizam os investimentos.A sociedade sofre mudanças radicais e, talvez, de proporções maiores do que as ocorridas em séculos passados. Não existe bola de cristal, mas algo é certo: a perspectiva global de transformações transcende nossa realidade imediata. Aconteça o que acontecer,só existem duas alternativas: segurança ou independência financeira. E o objetivo de Pai Rico, Pai Pobre é instruir o leitor e despertar sua inteligência financeira e a de seus filhos.“A principal razão pela qual as pessoas têm problemas financeiros é que passaram anos na escola, mas não aprenderam nada sobre dinheiro. O resultado é que elas aprendem a trabalhar por dinheiro… mas nunca a fazê-lo trabalhar para elas.” - Robert Kiyosaki.'},

    # LIVRO 13
    'Peppa Pig - Diversão em família': {'paginas': '60', 'autor': 'Ciranda Cultural', 'genero': 'Infantil',
                                        'preco': '22.90', 'editora': 'Cirando Cultural', 'avaliacao': '4.9', 'data': '16/01/2019', 'posicao': '13',
                                        'sinopse': 'Todos os dias, a família Pig tem uma aventura diferente. A cada descoberta, Peppa e seus amigos têm um novo desafio para lá de divertido e também muita história para contar. Compartilhe a leitura dos minilivros com a sua fami´lia e conheça um pouco mais sobre o universo de Peppa Pig.'},

    # LIVRO 14
    'Mais Esperto que o Diabo: O mistério revelado da liberdade e do sucesso': {'paginas': '208', 'autor': 'Napoleon Hill', 'genero': 'Autoajuda',
                                                                                'preco': '27.90', 'editora': 'Citadel', 'avaliacao': '4.7', 'data': '10/07/2014', 'posicao': '14',
                                                                                'sinopse': 'Neste livro, inédito no Brasil, você vai descobrir, após 75 anos de segredo, por meio dessa entrevista exclusiva que Napoleon Hill fez, quebrando o código secreto da mente do Diabo: Quem é o Diabo? Onde ele habita? Quais suas principais armas mentais? Quem são os alienados e de que forma eles ou elas se alienam? De que forma o Diabo influencia a nossa vida do dia a dia? Como a sua dominação influencia nossas atitudes? O que é o medo? Como nossos líderes religiosos e nossos professores são afetados pelo Diabo? Quais as armas que nós, seres humanos, possuímos para combater a dominação do Diabo? Qual a visão do Diabo sobre a energia sexual? Como buscar uma vida cheia de realizações, valorizando a felicidade e a liberdade? Essas perguntas e muitas outras são respondidas pelo próprio Diabo, que se autodenomina "Sua Majestade", de acordo com Napoleon Hill. O seu propósito, escrito com suas próprias palavras, é ajudar o ser humano a descobrir o seu real potencial, desvendando as armadilhas mentais que os homens e as mulheres deste mundo criam para si mesmos, sabotando a sua própria liberdade e o seu próprio direito de viver uma vida cheia de desafios, alegria e liberdade. Escrito em 1938, após uma das maiores crises econômicas, e precedendo a Segunda Guerra Mundial, este livro não somente é uma fonte de inspiração e coragem, mas deve ser considerado um manual para todas aquelas pessoas que desejam'},

    # LIVRO 15
    'A Rainha Vermelha': {'paginas': '424', 'autor': 'Victoria Aveyard', 'genero': 'Fantasia',
                          'preco': '23.90', 'editora': 'Seguinte', 'avaliacao': '4.7', 'data': '09/06/2015', 'posicao': '15',
                          'sinopse': 'O mundo de Mare Barrow é dividido pelo sangue: vermelho ou prateado. Mare e sua família são vermelhos: plebeus, humildes, destinados a servir uma elite prateada cujos poderes sobrenaturais os tornam quase deuses. Mare rouba o que pode para ajudar sua família a sobreviver e não tem esperanças de escapar do vilarejo miserável onde mora. Entretanto, numa reviravolta do destino, ela consegue um emprego no palácio real, onde, em frente ao rei e a toda a nobreza, descobre que tem um poder misterioso… Mas como isso seria possível, se seu sangue é vermelho? Em meio às intrigas dos nobres prateados, as ações da garota vão desencadear uma dança violenta e fatal, que colocará príncipe contra príncipe - e Mare contra seu próprio coração.'},

    # LIVRO 16
    'A Coragem de Ser Imperfeito': {'paginas': '208', 'autor': 'Brené Brown', 'genero': 'Autoajuda',
                                    'preco': '29.89', 'editora': 'Sextante', 'avaliacao': '4.7', 'data': '19/06/2016', 'posicao': '16',
                                    'sinopse': 'Viver é experimentar incertezas, riscos e se expor emocionalmente. Mas isso não precisa ser ruim. Como mostra Brené Brown, a vulnerabilidade não é uma medida de fraqueza, mas a melhor definição de coragem. Quando fugimos de emoções como medo, mágoa e decepção, também nos fechamos para o amor, a aceitação e a criatividade. Por isso, as pessoas que se defendem a todo custo do erro e do fracasso acabam se frustrando e se distanciando das experiências marcantes que dão significado à vida. Por outro lado, as que se expõem e se abrem para coisas novas são mais autênticas e realizadas, ainda que se tornem alvo de críticas e de inveja. É preciso lidar com os dois lados da moeda para se ter uma vida plena. Em sua pesquisa pioneira sobre vulnerabilidade, Brené Brown concluiu que fazemos uso de um verdadeiro arsenal contra a vergonha de nos expor e a sensação de não sermos bons o bastante, e que existem estratégias eficazes para serem usadas nesse “desarmamento”. Neste livro, ela apresenta suas descobertas e estratégias bem-sucedidas, toca em feridas delicadas e provoca grandes insights, desafiando-nos a mudar a maneira como vivemos e nos relacionamos.'},
    # LIVRO 17
    'JojoS Bizarre Adventure – Parte 4 – Diamond Is Unbreakable Volume 1': {'paginas': '304', 'autor': 'Hirohiko Araki', 'genero': 'Mangá HQs',
                                                                            'preco': '24.9', 'editora': 'Panini', 'avaliacao': '4.8', 'data': '05/06/2021', 'posicao': '17',
                                                                            'sinopse': 'Josuke Higashikata é um estudante colegial que vive na cidade de Morioh. Ao contrário do que aparenta, ele é um rapaz tímido, mas que muda completamente quando alguém insulta seu penteado, manifestando a habilidade de seu stand. Jotaro Kujo vai ao seu encontro ao descobrir que ele é parente de Jonathan e, ao ver seu stand, alerta Josuke sobre o perigo que se aproxima dele e da cidade.'},

    # LIVRO 18
    'Your Name': {'paginas': '496', 'autor': 'Makoto Shinkai e Ranmaru Kotone', 'genero': 'Anime',
                  'preco': '37.90', 'editora': 'JBC', 'avaliacao': '4.9', 'data': '23/10/2020', 'posicao': '18',
                  'sinopse': 'Edição única que reúne os três volumes do mangá baseado em Your Name, um dos filmes animados de maior sucesso da história do Japão.'},

    # LIVRO 19
    'Pulp': {'paginas': '80', 'autor': 'Ed Brubaker', 'genero': 'Mistério',
             'preco': '48.90', 'editora': 'Mino', 'avaliacao': '4.7', 'data': '21/07/2021', 'posicao': '19',
             'sinopse': 'Chega ao Brasil pela MINO um dos mais recentes e elogiados trabalhos da consagrada parceria entre Ed Brubaker e Sean Phillips, criadores de fenômenos como Kill or be Killed, My Heroes Have Always Been Junkies e Criminal. Max Winters, um escritor pulp na Nova York dos anos 1930, se vê atraído por uma história não muito diferente dos contos que ele produz a 5 centavos por palavra - contos de um fora da lei do oeste selvagem que faz justiça com seu revólver. Mas será que Max vai ser capaz de fazer o mesmo, quando perseguido por ladrões de banco, espiões nazistas e inimigos de seu passado? Parte thriller, parte meditação sobre uma vida de violência, PULP é diferente de tudo que a premiada dupla já fez. Uma celebração à ficção popular, ambientada em um mundo à beira do precipício.'},

    # LIVRO 20
    'Vermelho, Branco e Sangue Azul': {'paginas': '392', 'autor': 'Casey McQuiston', 'genero': 'Ficçao',
                                       'preco': '34.90', 'editora': 'Seguinte', 'avaliacao': '4.8', 'data': '04/11/2019', 'posicao': '20',
                                       'sinopse': 'O que pode acontecer quando o filho da presidenta dos Estados Unidos se apaixona pelo príncipe da Inglaterra? Quando sua mãe foi eleita presidenta dos Estados Unidos, Alex Claremont-Diaz se tornou o novo queridinho da mídia norte-americana. Bonito, carismático e com personalidade forte, Alex tem tudo para seguir os passos de seus pais e conquistar uma carreira na política, como tanto deseja. Mas quando sua família é convidada para o casamento real do príncipe britânico Philip, Alex tem que encarar o seu primeiro desafio diplomático: lidar com Henry, irmão mais novo de Philip, o príncipe mais adorado do mundo, com quem ele é constantemente comparado ― e que ele não suporta. O encontro entre os dois sai pior do que o esperado, e no dia seguinte todos os jornais do mundo estampam fotos de Alex e Henry caídos em cima do bolo real, insinuando uma briga séria entre os dois. Para evitar um desastre diplomático, eles passam um fim de semana fingindo ser melhores amigos e não demora para que essa relação evolua para algo que nenhum dos dois poderia imaginar ― e que não tem nenhuma chance de dar certo. Ou tem? “Vermelho, branco e sangue azul é escandalosamente divertido. É romântico, sexy, espirituoso e emocionante. Amei cada segundo.” ― Taylor Jenkins Reid, autora de Daisy Jones & The Six e Os sete maridos de Evelyn Hugo'},

    # LIVRO 21
    'O Milagre da Manhã: O segredo para transformar sua vida (antes das 8 horas)': {'paginas': '196', 'autor': 'Hal Elrod', 'genero': 'Autoajuda',
                                                                                    'preco': '20.40', 'editora': 'BestSeller', 'avaliacao': '4.7', 'data': '19/07/2016', 'posicao': '21',
                                                                                    'sinopse': 'O segredo para transformar sua vida antes das 8 horas. O best-seller com mais de 1 milhão de exemplares vendidos no Brasil. Neste novo clássico da autoajuda, Hal Elrod explica os benefícios de acordar cedo e desenvolver todo o nosso potencial e as nossas habilidades. O milagre da manhã permite que o leitor alcance níveis de sucesso jamais imaginados, tanto na vida pessoal quanto profissional. A mudança de hábitos e a nova rotina matinal proposta por Hal vão proporcionar melhorias significativas na saúde, na felicidade, nos relacionamentos, nas finanças, na espiritualidade ou quaisquer outras áreas que necessitem ser aprimoradas.E se você acordasse amanhã e percebesse que tem o poder de modificar qualquer área da sua vida?Acordando todo dia e praticando o desafio de transformação de vida de trinta dias de O milagre da manhã, você começará cada dia com níveis extraordinários de disciplina (a capacidade crucial para fazer com que você cumpra seus compromissos), clareza (o poder que você vai gerar se concentrando no que é mais importante) e desenvolvimento pessoal (talvez, o único fator determinante mais significativo para seu sucesso). Portanto, nos próximos trinta dias você se verá rapidamente se tornando a pessoa que precisa ser para criar os níveis extraordinários de sucesso pessoal, profissional e financeiro que realmente deseja.Você está pronto? O próximo capítulo do seu futuro - o futuro mais incrível que você já imaginou - está prestes a começar. Desenvolva seus objetivos a cada dia e comece a aproveitar todos os benefícios de O milagre da manhã! É hora de acordar e conquistar todo o seu potencial. Você merece uma vida extraordinária!'},

    # LIVRO 22
    'Quem pensa enriquece - o legado: O legado': {'paginas': '364', 'autor': 'Napoleon Hill', 'genero': 'Autoajuda',
                                                  'preco': '27.20', 'editora': 'Citadel', 'avaliacao': '4.8', 'data': '28/05/2018', 'posicao': '22',
                                                  'sinopse': 'O 9º livro mais vendido de todos os tempos, que influencia líderes e empreededores em todo o mundo, agora em uma edição especial atualizada para o século XXI. O clássico best-seller sobre o sucesso agora anotado e acrescido de exemplos modernos, comprovando que a filosofia da realização pessoal de Napoleon Hill permanece atual e ainda orienta aqueles que são bem-sucedidos. Um livro que vai mudar não só o que você pensa, vai mudar o modo como você pensa.'},

    # LIVRO 23
    'Box Trilogia O Senhor dos Anéis': {'paginas': '1568', 'autor': 'J. R. R.Tolkien', 'genero': 'Fantasia',
                                        'preco': '109.90', 'editora': 'HarperCollins', 'avaliacao': '4.9', 'data': '25/11/2019', 'posicao': '23',
                                        'sinopse': 'Apesar de ter sido publicado em três volumes – A Sociedade do Anel, As Duas Torres e O Retorno do Rei – desde os anos 1950, O Senhor dos Anéis não é exatamente uma trilogia, mas um único grande romance que só pode ser compreendido em seu conjunto, segundo a concepção de seu autor, J.R.R. Tolkien. Com design cuidadosamente pensado para refletir a unidade da obra e os desenhos originais feitos por Tolkien para as capas de cada volume, este box reúne os três livros da Saga do Anel e oferece aos leitores uma nova oportunidade de mergulhar no notável mundo da Terra-média.'},

    # LIVRO 24
    'Bruxa Natural': {'paginas': '256', 'autor': 'Arin Murphy-Hiscock', 'genero': 'Religião',
                      'preco': '43.65', 'editora': 'Darkside', 'avaliacao': '4.9', 'data': '15/04/2021', 'posicao': '24',
                      'sinopse': 'A figura da bruxa fascina a humanidade há gerações. A crença em bruxas e na magia permeava antigas civilizações e aparece até mesmo na Bíblia. Mulheres independentes e multifacetadas que cultivavam tradições de afinidade com a natureza e foram injustamente acusadas de malefícios. Curandeiras, benzedeiras, avós, mães. O que é ser uma bruxa natural, afinal de contas? É apropriar-se da força interior? É honrar a ancestralidade? É enxergar potencial mágico no mundano? Para a autora Arin Murphy-Hiscock, ser uma bruxa natural é tudo isso ― e também estreitar o laço com a natureza e estabelecer uma conexão com sua potência. A DarkSide® Books apresenta o livro Bruxa Natural, um guia para quem deseja explorar os presentes da natureza e encontrar equilíbrio e harmonia, despertando a magia que está em todos nós. A verdadeira magia ― aquela que nos move, fortalece e inspira ― mora no mundo ao nosso redor: no cair da chuva, na calidez do sol, na calmaria das plantas. Temos um mundo de possibilidades às nossas mãos. Tudo que resta é aproveitá-las. Autora prolífica que atua há mais de vinte anos no campo da bruxaria e espiritualidade, Arin Murphy-Hiscock incorporou toda a sua bagagem neste livro. Com Bruxa Natural você aprenderá a desenvolver e nutrir a prática da bruxaria verde, com informações essenciais sobre ervas, plantas, árvores, cristais e outras magias. Para praticantes solitárias ou integrantes de um coven, para quem está começando ou já se embrenhou nos mistérios da bruxaria, para aqueles que seguem ou não alguma religião, Bruxa Natural reúne receitas, exercícios, sugestões de rituais e orientações para fazer poções e misturas de ervas. “A bruxa natural trabalha ao lado da natureza e de seus dons [para] descobrir como conectar sua vida moderna com os conhecimentos antigos, que anseiam para serem redescobertos”, escreve a autora. Bruxa Natural nos ensina a ativar a sabedoria ancestral que corre em nossas veias. Seja bruxa. Coleção Magicae na DarkSide Books Magicae celebra a vida, as fases da lua, as marés internas e os mistérios dos oráculos. Livros repletos de encantamento que honram os poderes ancestrais e cultuam as leis da natureza. A magia que mora no farfalhar das folhas, na alquimia dos aromas, no sopro do vento e no virar das páginas também existe em todos nós. Magicae é o reencontro com a nossa própria essência.'},

    # LIVRO 26
    'Os segredos da mente milionária': {'paginas': '176', 'autor': 'T. Harv Eker', 'genero': 'Autoajuda',
                                        'preco': '27.55', 'editora': 'Editora Sextante', 'avaliacao': '4.8', 'data': '01/08/1992', 'posicao': '26',
                                        'sinopse': 'Se as suas finanças andam na corda bamba, talvez esteja na hora de você refletir sobre o que T. Harv Eker chama de "o seu modelo de dinheiro" – um conjunto de crenças que cada um de nós alimenta desde a infância e que molda o nosso destino financeiro, quase sempre nos levando para uma situação difícil.'},

    # LIVRO 27
    'Essencialismo': {'paginas': '272', 'autor': 'Greg Mckeown', 'genero': 'Autoajuda',
                      'preco': '33.70', 'editora': 'Sextante', 'avaliacao': '4.8', 'data': '15/05/2015', 'posicao': '27',
                      'sinopse': 'O ESSENCIALISTA NÃO FAZ MAIS COISAS EM MENOS TEMPO – ELE FAZ APENAS AS COISAS CERTAS.\nSe você se sente sobrecarregado e ao mesmo tempo subutilizado, ocupado, mas pouco produtivo, e se o seu tempo parece servir apenas aos interesses dos outros, você precisa conhecer o essencialismo.\n O essencialismo é mais do que uma estratégia de gestão de tempo ou uma técnica de produtividade. Trata-se de um método para identificar o que é vital e eliminar todo o resto, para que possamos dar a maior contribuição possível àquilo que realmente importa.\n\
                      Quando tentamos fazer tudo e ter tudo, realizamos concessões que nos afastam da nossa meta. Se não decidimos onde devemos concentrar nosso tempo e nossa energia, outras pessoas – chefes, colegas, clientes e até a família – decidem por nós, e logo perdemos de vista tudo o que é significativo.\nNeste livro, Greg McKeown mostra que, para equilibrar trabalho e vida pessoal, não basta recusar solicitações aleatoriamente: é preciso eliminar o que não é essencial e se livrar de desperdícios de tempo. Devemos aprender a reduzir, simplificar e manter o foco em nossos objetivos.\nQuando realizamos tarefas que não aproveitam nossos talentos e assumimos compromissos só para agradar aos outros, abrimos mão do nosso poder de escolha. O essencialista toma as próprias decisões – e só entra em ação se puder fazer a diferença.'},

    # LIVRO 28
    'Admirável mundo novo': {'paginas': '312', 'autor': 'Aldous Leonard Huxley', 'genero': 'Ficção',
                             'preco': '21.49', 'editora': 'Biblioteca Azul', 'avaliacao': '4.7', 'data': '01/01/2014', 'posicao': '28',
                             'sinopse': 'Um clássico moderno, o romance distópico de Aldous Huxley é incontornável para quem procura um dos exemplos mais marcantes da tematização de estados autoritários, ao lado de 1984, de George Orwell.\nEle mostra uma sociedade inteiramente organizada segundo princípios científicos, na qual a mera menção das antiquadas palavras “pai” e “mãe” produzem repugnância. Um mundo de pessoas programadas em laboratório, e adestradas para cumprir seu papel numa sociedade de castas biologicamente definidas já no nascimento. Um mundo no qual a literatura, a música e o cinema só têm a função de solidificar o espírito de conformismo. Um universo que louva o avanço da técnica, a linha de montagem, a produção em série, a uniformidade, e que idolatra Henry Ford. Essa é a visão desenvolvida no clarividente romance Huxley.\nAo lado de 1984, que criticava acidamente os governos totalitários de esquerda e de direita, o terror do stalinismo e a barbárie do nazifascismo, em Huxley o objeto é a sociedade capitalista, industrial e tecnológica, na qual a racionalidade se tornou a nova religião, a ciência é o novo ídolo, um mundo no qual a experiência do sujeito não parece mais fazer nenhum sentido, e no qual a obra de Shakespeare adquire tons revolucionários.\nEntretanto, o moderno clássico de Huxley não é um mero exercício de futurismo ou de ficção científica. Trata-se, o que é mais grave, de um olhar agudo acerca das potencialidades autoritárias do próprio mundo em que vivemos. Como um alerta de que, ao não se preservarem os valores da civilização humanista, o que nos aguarda não é o róseo paraíso iluminista da liberdade, mas os grilhões de um admirável mundo novo.'},

    # LIVRO 29
    'Como fazer amigos e influenciar pessoas': {'paginas': '256', 'autor': 'Dale Carnegie', 'genero': 'Autoajuda',
                                                'preco': '29.99', 'editora': 'Sextante', 'avaliacao': '4.8', 'data': '08/10/2019', 'posicao': '29',
                                                'sinopse': 'Um dos maiores clássicos de todos os tempos, Como fazer amigos e influenciar pessoas é considerado a Bíblia dos relacionamentos interpessoais. “O livro de autoajuda mais bem-sucedido de todos os tempos. Carnegie nunca foi tão relevante.” – The Times Mais de 16 milhões de livros vendidos. Ao longo de oito décadas, este livro se tornou a referência quando o assunto é o desenvolvimento das relações humanas, das habilidades sociais e da comunicação eficiente. Partindo do princípio de que é preciso se interessar genuinamente por aqueles com quem interagimos, ele mudou a vida de milhões de pessoas, fazendo-as se sentirem mais seguras, abertas e confiantes em seus encontros sociais e profissionais. Com saborosas histórias, exemplos práticos e ótimos conselhos, esta é uma leitura prazerosa e fundamental para quem deseja criar bons vínculos, se tornar mais persuasivo, deixar uma marca positiva e inspirar os outros com energia e gentileza.'},

    # LIVRO 30
    'Especialista em pessoas: Soluções bíblicas e inteligentes para lidar com todo tipo de gente': {'paginas': '224', 'autor': 'Tiago Brunet', 'genero': 'Autoajuda',
                                                                                                    'preco': '23.90', 'editora': 'Academia', 'avaliacao': '4.8', 'data': '28/02/2020', 'posicao': '30',
                                                                                                    'sinopse': 'Algumas pessoas ferem, outras curam. Não desista das pessoas!\nNo mundo ideal as pessoas amam umas às outras, ninguém julga para não ser julgado.\nA família, nesse lugar, é a que mais preserva os familiares, e aqueles que nos ofendem e perseguem são perdoados sem demora ou ressentimentos. Contudo, no mundo real, as coisas não funcionam assim ainda.\nEnquanto vivemos esta batalha“ideal” versus “real”, precisamos aprender a sobreviver no mundo tal como ele se apresenta diante de nós. É nesse mundo que vivemos agora.\nNeste mundo real, a inveja é forte, os haters e críticos são profissionais e a fofoca flui em velocidade de internet banda larga.\nNeste mundo, temos mais desgastes emocionais com pessoas do que alegria com elas. Isso faz sentido pra você?\nNossos olhos podem mirar o mundo ideal, ter como meta viver como se ali estivesse; porém é preciso que nossa mente e nosso coração estejam vacinados contra as epidemias emocionais do mundo real que tentam nos infectar.\nÉ importante que você entenda que este livro foi escrito para este tempo, a vida que temos no mundo real.\nO método que já ajudou milhões de pessoas em palestras, em mais de 30 países, em suas mãos!'},

    # LIVRO 31
    'Os sete maridos de Evelyn Hugo': {'paginas': '360', 'autor': 'Taylor Jenkins Reid', 'genero': 'Ficção',
                                       'preco': '28.32', 'editora': 'Paralela', 'avaliacao': '4.8', 'data': '21/10/2019', 'posicao': '31',
                                       'sinopse': 'Com todo o esplendor que só a Hollywood do século passado pode oferecer, esta é uma narrativa inesquecível sobre os sacrifícios que fazemos por amor, o perigo dos segredos e o preço da fama.\nLendária estrela de Hollywood, Evelyn Hugo sempre esteve sob os holofotes ― seja estrelando uma produção vencedora do Oscar, protagonizando algum escândalo ou aparecendo com um novo marido… pela sétima vez. Agora, prestes a completar oitenta anos e reclusa em seu apartamento no Upper East Side, a famigerada atriz decide contar a própria história ― ou sua “verdadeira história” ―, mas com uma condição: que Monique Grant, jornalista iniciante e até então desconhecida, seja a entrevistadora. Ao embarcar nessa misteriosa empreitada, a jovem repórter começa a se dar conta de que nada é por acaso ― e que suas trajetórias podem estar profunda e irreversivelmente conectadas.'},

    # LIVRO 32
    '12 regras para a vida: Um antídoto para o caos': {'paginas': '448', 'autor': 'Jordan B. Peterson', 'genero': 'Autoajuda',
                                                       'preco': '33.99', 'editora': 'Alta Books', 'avaliacao': '4.8', 'data': '30/04/2018', 'posicao': '32',
                                                       'sinopse': 'Aclamado psicólogo clínico, Jordan Peterson tem influenciado a compreensão moderna sobre a personalidade e, agora, se transformou em um dos pensadores públicos mais populares do mundo, com suas palestras sobre tópicos que variam da bíblia, às relações amorosas e à mitologia, atraindo dezenas de milhões de espectadores. Em uma era de mudanças sem precedentes e polarização da política, sua mensagem franca e revigorante sobre o valor da responsabilidade individual e da sabedoria ancestral tem ecoado em todos os cantos do mundo. Neste livro, ele oferece doze princípios profundos e práticos sobre como viver uma vida com significado. A partir de exemplos vívidos de sua prática clínica e vida pessoal, bem como de lições extraídas das histórias e mitos mais antigos da humanidade, 12 Regras para a Vida oferece um antídoto para o caos em nossas vidas: verdades eternas aplicadas aos nossos problemas modernos.'},

    # LIVRO 33
    'O morro dos ventos uivantes': {'paginas': '368', 'autor': 'Emily Bronte', 'genero': 'Romance',
                                    'preco': '12.89', 'editora': 'Principis', 'avaliacao': '4.7', 'data': '17/06/2019', 'posicao': '33',
                                    'sinopse': 'Único romance da escritora inglesa Emily Bronte, O morro dos ventos uivantes retrata uma trágica historia de amor e obsessão em que os personagens principais são a obstinada e geniosa Catherine Earnshaw e seu irmão adotivo, Heathcliff. Grosseiro, humilhado e rejeitado, ele guarda apenas rancor no coração, mas tem com Catherine um relaciona- mento marcado por amor e, ao mesmo tempo, ódio. Essa ligação perdura mesmo com o casamento de Catherine com Edgar Linton.'},

    # LIVRO 34
    'Corte de espinhos e rosas': {'paginas': '434', 'autor': 'Sarah J Maas', 'genero': 'Fantasia',
                                  'preco': '35.89', 'editora': 'Galera', 'avaliacao': '4.8', 'data': '09/10/2015', 'posicao': '34',
                                  'sinopse': 'Ela roubou uma vida. Agora deve pagar com o coração. Corte de espinhos e rosas é primeiro volume da série best-seller, da mesma autora da saga Trono de vidro. Num mundo dividido uma muralha mágica separa duas espécies. De um lado, os feéricos vivem dentro de suas fronteiras cheias de beleza e mistério; do outro, os humanos possuem apenas medo, desconfiança e dificuldades.Feyre, filha de um casal de mercadores humanos e falidos, se torna caçadora para sustentar a família. Dura como as flechas que carrega, letal como sua pontaria, ela abandona as fantasias de garota e as troca pela árdua vida nas florestas ao redor de sua aldeia.Sua única alegria é observar as cores e sonhar em capturá-las. Mas, na floresta, coberta de neve tudo é branco e árido; como o ódio pelos feéricos que carrega no coração; Como as telas que não pode comprar ou colorir. Até que um enorme lobo cruza seu caminho... Sem hesitar, Feyre dispara... uma flecha. Um ato de rebelião.Após matar o lobo, uma criatura bestial surge exigindo uma reparação. Arrastada para além do muro, para uma terra mágica e traiçoeira - que ela só conhece por meio de lendas -, a jovem descobre que seu captor não é um animal, mas Tamlin, Grão Senhor da Terra Primaveril. Um feérico com um segredo, escondido sob uma máscara. Ela descobre ainda que o então animal que havia assassinado era, na verdade, uma criatura mágica, uma fada zoomórfica transformada em lobo.À medida que ela descobre mais sobre este mundo onde a magia impera, seus sentimentos por Tamlin passam da mais pura hostilidade até uma paixão avassaladora. Enquanto isso, uma sinistra e antiga sombra avança sobre o mund­­o das fadas e Feyre deve provar seu amor para detê-la ou Tamlin e seu povo estarão condenados.Corte de espinhos e rosas é um livro de fantasia de tirar o fôlego. Memorável em todos os aspectos, com personagens complexos, enredo rico e um magnífico mundo de fantasia combinados impecavelmente para criar um romance épico.'},

    # LIVRO 35
    'As cinco linguagens do amor': {'paginas': '216', 'autor': 'Gary Chapman', 'genero': 'Autoajuda',
                                    'preco': '28.90', 'editora': 'Mundo Cristão', 'avaliacao': '4.8', 'data': '12/06/2013', 'posicao': '35',
                                    'sinopse': 'As diferenças gritantes no jeito de ser e de agir de homens e mulheres já não são novidade há tempos. O que continua sendo um dilema é como fazer dar certo uma relação entre duas pessoas que às vezes parecem ter vindo de planetas distintos. Compreender essas diferenças é parte da solução e é nisso que Gary Chapman vai ajudar você. Com mais de 30 anos de experiência no aconselhamento de casais, ele percebeu que cada um de nós adota uma linguagem pela qual damos e recebemos amor. Quando o casal não entende corretamente a linguagem predominante de cada um, a comunicação é afetada, impedindo que se sintam amados, aceitos e valorizados. Nesta terceira edição de sua clássica obra sobre relacionamentos, que já vendeu mais de 8 milhões de exemplares, Gary Chapman não só explica as cinco linguagens como apresenta um questionário para os maridos e outro para as esposas descobrirem a sua linguagem de amor. Além disso, uma seção especial de perguntas e respostas vai esclarecer todas as suas dúvidas e lhe dar o direcionamento sobre como expressar melhor seu amor a seu cônjuge e ajudará você a compreender a forma dele manifestar o amor. Gary Chapman identificou cinco formas através das quais as pessoas expressam e recebem as manifestações de amor: palavras de afirmação; tempo de qualidade; presentes; atos de serviço; toque físico. Aprendam, você e seu cônjuge, a se comunicar através dessas linguagens e experimentem como é ser realmente amado e compreendido.'},

    # LIVRO 36
    'A liberdade é uma escolha: Lições práticas e inspiradoras para ajudar você a se libertar de suas prisões mentais': {'paginas': '176', 'autor': 'Edith Eva Eger', 'genero': 'Autoajuda',
                                                                                                                         'preco': '27.50', 'editora': 'Sextante', 'avaliacao': '4.7', 'data': '17/03/2021', 'posicao': '36',
                                                                                                                         'sinopse': 'Em seu primeiro livro, Edith Eva Eger emocionou o mundo ao contar como sobreviveu aos horrores da guerra e transformou seu sofrimento numa jornada de perdão e cura, ajudando milhares de pessoas a lidar com seus traumas mais profundos. Agora, em A liberdade é uma escolha, ela apresenta ensinamentos práticos que vão nos ajudar a identificar nossas próprias prisões mentais e a desenvolver as estratégias necessárias para nos libertarmos delas. Afinal, o que importa não é o que nos aconteceu, mas o que faremos de agora em diante e como poderemos encontrar na dor o aprendizado de que precisamos para seguir em frente. Este livro é uma verdadeira lição de esperança e superação – uma afirmação do poder que temos sobre nossa própria felicidade e um oportuno lembrete de que a liberdade é uma escolha que podemos fazer todos os dias, independentemente das circunstâncias.'},

    # LIVRO 37
    '': {'paginas': '', 'autor': '', 'genero': '',
         'preco': '', 'editora': '', 'avaliacao': '', 'data': '', 'posicao': '',
         'sinopse': ''},

    # LIVRO 38
    '': {'paginas': '', 'autor': '', 'genero': '',
         'preco': '', 'editora': '', 'avaliacao': '', 'data': '', 'posicao': '',
         'sinopse': ''},

    # LIVRO 39
    '': {'paginas': '', 'autor': '', 'genero': '',
         'preco': '', 'editora': '', 'avaliacao': '', 'data': '', 'posicao': '',
         'sinopse': ''},

    # LIVRO 40
    '': {'paginas': '', 'autor': '', 'genero': '',
         'preco': '', 'editora': '', 'avaliacao': '', 'data': '', 'posicao': '',
         'sinopse': ''},

    # LIVRO 41
    '': {'paginas': '', 'autor': '', 'genero': '',
         'preco': '', 'editora': '', 'avaliacao': '', 'data': '', 'posicao': '',
         'sinopse': ''},

    # LIVRO 42
    '': {'paginas': '', 'autor': '', 'genero': '',
         'preco': '', 'editora': '', 'avaliacao': '', 'data': '', 'posicao': '',
         'sinopse': ''},

    # LIVRO 43
    '': {'paginas': '', 'autor': '', 'genero': '',
         'preco': '', 'editora': '', 'avaliacao': '', 'data': '', 'posicao': '',
         'sinopse': ''},

    # LIVRO 44
    '': {'paginas': '', 'autor': '', 'genero': '',
         'preco': '', 'editora': '', 'avaliacao': '', 'data': '', 'posicao': '',
         'sinopse': ''},

    # LIVRO 45
    '': {'paginas': '', 'autor': '', 'genero': '',
         'preco': '', 'editora': '', 'avaliacao': '', 'data': '', 'posicao': '',
         'sinopse': ''},

    # LIVRO 46
    '': {'paginas': '', 'autor': '', 'genero': '',
         'preco': '', 'editora': '', 'avaliacao': '', 'data': '', 'posicao': '',
         'sinopse': ''},

    # LIVRO 47
    '': {'paginas': '', 'autor': '', 'genero': '',
         'preco': '', 'editora': '', 'avaliacao': '', 'data': '', 'posicao': '',
         'sinopse': ''},

    # LIVRO 48
    '': {'paginas': '', 'autor': '', 'genero': '',
         'preco': '', 'editora': '', 'avaliacao': '', 'data': '', 'posicao': '',
         'sinopse': ''},

    # LIVRO 49
    '': {'paginas': '', 'autor': '', 'genero': '',
         'preco': '', 'editora': '', 'avaliacao': '', 'data': '', 'posicao': '',
         'sinopse': ''},

    # LIVRO 50
    '': {'paginas': '', 'autor': '', 'genero': '',
         'preco': '', 'editora': '', 'avaliacao': '', 'data': '', 'posicao': '',
         'sinopse': ''}
}
